# Pertemuan 3

Membuat list dengan mengambil system time

In [ ]:
from datetime import datetime as dt

cdt = dt.now()
date = '%s/%s/%s' % (cdt.day, cdt.month, cdt.year)
mahasiswa = ['Char Aznable', '2022071000', 'Desain dan Analisis Algoritma', date, 'Universitas Pembangunan Jaya']

print(mahasiswa)

['Char Aznable', '2022071000', 'Desain dan Analisis Algoritma', '13/9/2023', 'Universitas Pembangunan Jaya']


In [ ]:
bin_colors= ['red', 'green', 'blue', 'yelllow']
bin_colors[1]

'green'

In [ ]:
print('Nama\t\t: ', mahasiswa[0], '\nNIM\t\t: ', mahasiswa[1], '\nInstitusi\t: ', mahasiswa[4])

Nama		:  Char Aznable 
NIM		:  2022071000 
Institusi	:  Universitas Pembangunan Jaya


In [ ]:
print(mahasiswa[1:3])

print('\n')

for x in range(1, 3):
  print(mahasiswa[x])


['2022071000', 'Desain dan Analisis Algoritma']


2022071000
Desain dan Analisis Algoritma


In [ ]:
for a in bin_colors:
  print(a + ' gasih')

red gasih
green gasih
blue gasih
yelllow gasih


Nested Tuple 1

In [ ]:
upj = ('Universitas', 'Pembangunan', 'Jaya')
hariAwal = ('senin', 'selasa', 'rabu')
hariAkhir = ('kamis', 'jumat', 'sabtu')

hari = (hariAwal, hariAkhir)
print(hari)

(('senin', 'selasa', 'rabu'), ('kamis', 'jumat', 'sabtu'))


Nested Tuple 2

In [ ]:
pertama = (100)
kedua = (200, 400, 600)
ketiga = (300)
keempat = (400, 800)

nested_tuple = (pertama, kedua, ketiga, keempat)
print(nested_tuple)

(100, (200, 400, 600), 300, (400, 800))


# SETS IN PYTHON

In [9]:
set_01 = {4,5,6,2}
print(set_01)

set_02 = set()
set_03 = set([2,1,4,3])
print(type(set_02))
print(set_03)

set_03.add(31)
print(set_03)

{2, 4, 5, 6}
<class 'set'>
{1, 2, 3, 4}
{1, 2, 3, 4, 31}


Set Union, Intersection, Difference

In [12]:
set_A = {1,2,3,4}
set_B = {3,4,5,6}

# Union
print(set_A|set_B)
print(set_A.union(set_B))

# Intersection
print(set_A & set_B)
print(set_A.intersection(set_B))

# Difference
print(set_A - set_B)
print(set_A.difference(set_B))

print(set_B - set_A)
print(set_B.difference(set_A))

print(set_A ^ set_B)
print(set_A.symmetric_difference(set_B))

{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}
{3, 4}
{3, 4}
{1, 2}
{1, 2}
{5, 6}
{5, 6}
{1, 2, 5, 6}
{1, 2, 5, 6}


# Dictionary

In [ ]:
data = {'Nama': 'Amuro', 'NIM': '00', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}
print(data)
data['NIM'] = '01'
print(data)

{'Nama': 'Amuro', 'NIM': '00', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}
{'Nama': 'Amuro', 'NIM': '01', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


# Data Frame

In [13]:
import pandas as pd

mhs = pd.DataFrame({'Prodi': ['Informatika', 'Sistem Informasi', 'Teknik  Sipil'], 'Mahasiswa': [50, 55, 40], 'Laki-laki': [30, 30, 30], 'Perempuan': [20, 25, 10]})
print(type(mhs))
mhs.head()

<class 'pandas.core.frame.DataFrame'>


Prodi  Mahasiswa  Laki-laki  Perempuan
0       Informatika         50         30         20
1  Sistem Informasi         55         30         25
2     Teknik  Sipil         40         30         10

# Matrix

In [17]:
import numpy as np

myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(type(myMatrix))
print(myMatrix)
print("")
print(np.transpose(myMatrix))

<class 'numpy.ndarray'>
[[11 12 13]
 [21 22 23]
 [31 32 33]]

[[11 21 31]
 [12 22 32]
 [13 23 33]]
